//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalPlatform.Models.BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsocieriProfMaterieClasa
    {
        public int AsocieriProfMaterieClasaID { get; set; }
        public Nullable<int> ProfesorID { get; set; }
        public Nullable<int> MaterieID { get; set; }
        public Nullable<int> ClasaID { get; set; }
    
        public virtual Clase Clase { get; set; }
        public virtual Materii Materii { get; set; }
        public virtual Profesori Profesori { get; set; }
    }
}
