//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalPlatform.Models.BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clase()
        {
            this.AsocieriProfMaterieClasa = new HashSet<AsocieriProfMaterieClasa>();
        }
    
        public int ClasaID { get; set; }
        public string NumeClasa { get; set; }
        public Nullable<int> AnStudiu { get; set; }
        public Nullable<int> DiriginteID { get; set; }
        public Nullable<int> SpecializareID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsocieriProfMaterieClasa> AsocieriProfMaterieClasa { get; set; }
        public virtual Diriginti Diriginti { get; set; }
        public virtual Specializari Specializari { get; set; }
    }
}
